baseURL: "https://yourusername.github.io/" 
title: Your Name
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: "#"
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://yourblog.com
          weight: 6

params:
    description: "This website hosts my research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Your Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Your Name
          subtitle: "Brief description of your position and research interests. Include your academic background and current affiliation here."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: "#"
            - name: Data
              url: "#"
            - name: Books
              url: "#"
            - name: Courses
              url: "#"
            - name: Tags
              url: "#"
            - name: Archive
              url: "#"
            - name: Blog
              url: "#"

    socialIcons:
        - name: CV
          url: 
        - name: Email
          url:
        - name: Google Scholar
          url:
        - name: GitHub
          url:
        - name: Twitter
          url:

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Your Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2